
<?php /** @var \Primfix\Counter\Block\Index\ $block */ ?>
<h2>
    <?= $block->getModuleRealName() ?>
</h2>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate eveniet quisquam officia quaerat ullam vero voluptatem id rem. Porro, a. Temporibus reprehenderit omnis voluptatibus sed, recusandae iste vero illo eligendi?
Ratione repudiandae sit eaque est odit, dicta delectus neque fugit nihil quibusdam, libero quisquam architecto quis aliquam laborum recusandae ex saepe pariatur illo nisi consequuntur optio quasi! Labore, dolorem sit.
Minima ipsa quod eius accusamus itaque quas quidem, mollitia quibusdam soluta ad! Aliquid ad cupiditate reprehenderit molestiae, aperiam doloribus labore obcaecati, quam, tenetur adipisci in vero animi expedita praesentium. At.

<?= $block->_getChildHtml('primfix_nested') ?>